#!/bin/sh
#
# [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint) is the default
# initial process which and executes all the applications and services that run in a container.
#
# This is the default ENTRYPOINT located at `/usr/sbin/entrypoint` and should be 
# augmented when used in downstream containers by over writting the `/etc/container/entrypoint` 
# file (which by default is a symlink to `/mnt/volumes/container/entrypoint`
#

echo
echo

ENTRYPOINT_PARAMS="$@"
# . /etc/profile

echo "Enter container($(cat /etc/debian_version) as [$(/usr/bin/whoami)])"

/usr/bin/pgrep crond > /dev/null
TEST=$?
if [ $TEST -eq 1 ] ; then
 echo " - Launch cron"
 cron
 RTN=$?
 if [ $RTN -ne 0 ] ; then
  echo "Application (cron) failed to start"
  return 3
 fi
fi
 
. /etc/container/entrypoint
# if [ -z $ENTRYPOINT_PARAMS ] ; then
#  echo "Launch application as detatched"
#  app_entrypoint ENTRYPOINT_PARAMS >> /mnt/volumes/container/_log 2>&1 &
# exec $ENTRYPOINT_PARAMS
# else
#  echo "Launch blocking application"
#  app_entrypoint ENTRYPOINT_PARAMS 
# fi

# echo $ENTRYPOINT_PARAMS
/usr/bin/zsh
